CREATE TABLE IF NOT EXISTS crm_clients (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  initials VARCHAR(10),
  location VARCHAR(255),
  address TEXT,
  phone VARCHAR(50),
  email VARCHAR(255) UNIQUE NOT NULL,
  status VARCHAR(50) DEFAULT 'active',
  password VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS crm_pets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  client_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  breed VARCHAR(255),
  type VARCHAR(50),
  origin VARCHAR(255),
  destination VARCHAR(255),
  image TEXT,
  status VARCHAR(100),
  status_color VARCHAR(100),
  details TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES crm_clients(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS crm_documents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  client_id INT NOT NULL,
  pet_id INT,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(100),
  expiry_date VARCHAR(50),
  status VARCHAR(50),
  icon VARCHAR(50),
  file_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES crm_clients(id) ON DELETE CASCADE,
  FOREIGN KEY (pet_id) REFERENCES crm_pets(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS crm_quotes (
  id VARCHAR(50) PRIMARY KEY,
  client_id INT NOT NULL,
  ref VARCHAR(50),
  route TEXT,
  status VARCHAR(50) DEFAULT 'Awaiting Approval',
  pet_quotes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES crm_clients(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS crm_journeys (
  id VARCHAR(50) PRIMARY KEY,
  client_id INT NOT NULL,
  pet_id INT NOT NULL,
  overall_progress INT DEFAULT 0,
  current_location VARCHAR(255),
  estimated_arrival VARCHAR(255),
  airline VARCHAR(255),
  flight_no VARCHAR(50),
  tracking_id VARCHAR(100),
  stages TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES crm_clients(id) ON DELETE CASCADE,
  FOREIGN KEY (pet_id) REFERENCES crm_pets(id) ON DELETE CASCADE
);
